### ISSUE TITLE
Add to Firefox Add-Ons store

### ISSUE THREAD

**Issue by ned** [itayperl/jisho-forvo#1]
Can you release this to the Firefox Add-ons store? Chrome doesn't support extensions on mobile, but I use my phone a lot for learning Japanese, so having it available for Firefox would be really useful.

**Comment by itayperl** [comment]
[Done!](https://addons.mozilla.org/en-US/firefox/addon/jisho-forvo/)

**Comment by ned** [comment]
Thank you!
